export const balconySunset = 'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-sunset.jpg';
export const lowerPool = 'https://s3.amazonaws.com/spainluxury.holiday-assets/lower-pool.jpg';
export const secondBedroom = 'https://s3.amazonaws.com/spainluxury.holiday-assets/second-bedroom.jpg';
export const upperPoolAtNight = 'https://s3.amazonaws.com/spainluxury.holiday-assets/upper-pool-at-night.jpg';

export const pictures = [
  'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-east-view.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-west-view.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-wide-view.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-recliners.webp',
  balconySunset,
  'https://s3.amazonaws.com/spainluxury.holiday-assets/balcony-view-night.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/building-view-from-below.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/community-walkway.avif',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/gate.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/couch.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/kitchen-counter.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/kitchen-table.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/living-room-2.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/living-room.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/main-bedroom.jpg',
  secondBedroom,
  'https://s3.amazonaws.com/spainluxury.holiday-assets/second-bedroom-window.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/master-bathroom.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/bathroom-sinks.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/second-bathroom.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/nespresso.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/smart-tv-2.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/smart-tv.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/lower-pool-2.jpg',
  lowerPool,
  'https://s3.amazonaws.com/spainluxury.holiday-assets/lower-pool.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/sea-view-daytime.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/sea-view.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/pool-grass.jpg',
  upperPoolAtNight,
  'https://s3.amazonaws.com/spainluxury.holiday-assets/community-from-window.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/pool-trees.webp',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/sea-view-daytime-2.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/second-bedroom-2.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/front-door.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/kitchen-2.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/kitchen-table-2.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/kitchen.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/second-bedroom-closet.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/shower.jpg',
  'https://s3.amazonaws.com/spainluxury.holiday-assets/sunset.webp',
];
